language: ruby
rvm:
- 2.4.1
# - jruby

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

deploy:
  provider: heroku
  api_key:
    secure: "CRzkUMY/yjLiOLFLi4Dhk4Z/GqdJS+Mb+9A0m0UBX88Q/VyHtAAUrOAWhg0aJw9UymUpQQmK17om2A0Ka7DVDUOzIuqiOWx2oLl0ETUdNOG/ZcBE+/lesgxHBSUyraX2o0InRBwI07aealIP/ItIK48PPqDoc0BPQdK6wU4xjD5BHnrIXj1lFA6yD7XMhqL9qhTmb56bjmX2nAejEXEwITFaAcBVJ5xUithlx2g9/UOUcC4AZ3ZZPtjOIaR4K7IQYaRYWY6+VgxKUIvDP1JHrG+qbBSKZgpqiTXbsuw/IUjeVCQ9NCNc/iWGB4zqo9t8FpI5Buc/Irbbs6K6TgMEl5jB4AH2aWiuPkRU5GrZsnVDygyErwhyLYU4y8jjgsI9gdNI65ac1CSz4ZGSbIZjuavunA4y63ty9TBLlvP0up9itWeNUScW6YEe/v6sO8SOr7DR7HliyQ59/l4YmYnjvpJPVycbvT/i0sy/DMJFoVAg/0yIfdkEvzxvPT95pAUPXaR0L2fFdfe8X7n23VlnxpCC2C2lk8ttuFQI1wg7PQX1kOpn//5Gu+mJ2Oc81VXtJFbnb6qjS+HTU9a7UXNK5SQ1KAe2lTIDLrPlR720SCCTwGrKmSBuf+sdCjG8PkLr0P2aSz4hFQax/5f+jEFTcXzCCqpS4WrUXfhRoTZpe0k="
